### ISSUE TITLE
As maintainer, I want to separate the Storefront from the CMS, so that I can manage each project separately.

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/platform-mon-storefront#127]
### Acceptance Criteria

- [x] The storefront doesn't use the CMS from the same project.
- [x] The CMS URL is configured in environment variables

### Tasks

- [x] create a new repo with the CMS
- [x] #128
- [x] #129
